branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration:
  - Release
  # - Debug

platform: x64
cache:
  - C:\deps
  - C:\deps\CGAL-5.0.2
  - C:\deps\OSGeo4W
  - C:\deps\eigen3.3.6

  
install:
  ############################################################################
  # All external dependencies are installed in C:\deps
  ############################################################################
  
    ############################################################################
  # Set boost variables
  ############################################################################
  - set BOOST_ROOT=C:\Libraries\boost_1_73_0
  - set BOOST_INCLUDEDIR=C:\Libraries\boost_1_73_0
  - set BOOST_LIBRARYDIR=C:\Libraries\boost_1_73_0\lib64-msvc-14.1
   
  
  - set DEPS_DIR=C:\deps
  - if not exist %DEPS_DIR%
      mkdir %DEPS_DIR%
  
   
  
#only run the download and unzip at the first time, uncomment line 42-95  
#At the second time you do not need to download again because it already stores in the cache. 

  #install Eigen 3.3.6
  - appveyor DownloadFile http://bitbucket.org/eigen/eigen/get/3.3.6.zip -FileName eigen.zip
  - 7z x eigen.zip -o"C:\deps" > nul   
  - mv C:\deps\eigen-eigen-b70bf4fad467 C:\deps\eigen3.3.6

  - set EIGEN3_INCLUDE_DIR = C:\deps\eigen3.3.6
  - set PATH=%EIGEN3_INCLUDE_DIR%;%PATH%

  
 #  install CGAL
  - cd %DEPS_DIR%    
  - set CGAL_DIR=%DEPS_DIR%\CGAL-5.0.2
  
  - appveyor DownloadFile https://github.com/CGAL/cgal/releases/download/releases/CGAL-5.0.2/CGAL-5.0.2.zip -FileName CGAL-5.0.2.zip
  - 7z x CGAL-5.0.2.zip -o"C:\deps" > nul
  
  - cd C:\deps
  - ls -a   
  - pwd
   
  - appveyor DownloadFile https://www.dropbox.com/s/okbl2nvdj36y31i/gmp.zip?dl=1 -FileName gmp.zip
  - 7z x gmp.zip -aoa -o%CGAL_DIR%\auxiliary > nul
  
  

  
  
  - cd %CGAL_DIR% 
  - pwd
  - ls -a
  - cmake -G "Visual Studio 15 Win64" -S C:\deps\CGAL-5.0.2 -DBUILD_SHARED_LIBS=ON -DBoost_USE_STATIC_LIBS=OFF -DWITH_Eigen3=ON -DEIGEN3_INCLUDE_DIR=C:\deps\eigen3.3.6
  - cd %CGAL_DIR%
  - MSBUILD "C:\deps\CGAL-5.0.2\CGAL.sln" /property:Configuration=Release /property:Platform=x64 /verbosity:minimal
  #- cd %CGAL_DIR%
  #- MSBUILD "C:\deps\CGAL-4.14\CGAL.sln" /property:Configuration=Debug /property:Platform=x64 /verbosity:minimal

 
  - set PATH=%CGAL_DIR%;%PATH%
  - set PATH=%CGAL_DIR%\bin;%PATH%
  
  
  


  
  
  
    #install OSGeo4W
  - cd %DEPS_DIR%
  - set OSGEO4W_ROOT=%DEPS_DIR%\OSGeo4W
  - set LIBLAS_ROOT=%OSGEO4W_ROOT%
  - set LASZIP_ROOT=%OSGEO4W_ROOT%
  
  - appveyor DownloadFile http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe -FileName osgeo4w-setup-x86_64.exe
  - osgeo4w-setup-x86_64.exe -q -k -r -A -s http://download.osgeo.org/osgeo4w/ -a x86_64 -P liblas-devel,liblas,laszip,gdal -R %OSGEO4W_ROOT% > NUL
  - set PATH=%OSGEO4W_ROOT%\bin;%PATH%
  
  
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake -G "Visual Studio 15 Win64" -S %APPVEYOR_BUILD_FOLDER% -B %APPVEYOR_BUILD_FOLDER%\build -DCGAL_DIR=C:\deps\CGAL-5.0.2 -DGEOS_INCLUDE_DIR=%DEPS_DIR%\OSGeo4W\include -DGEOS_LIBRARY=%DEPS_DIR%\OSGeo4W\lib\geos_c.lib
    
        
  
      
build_script:
- cmd: msbuild %APPVEYOR_BUILD_FOLDER%\build\val3dity.sln /property:Configuration=Release /property:Platform=x64 /verbosity:minimal


after_build:
  - if exist %APPVEYOR_BUILD_FOLDER%\build\Release\val3dity.exe
    7z a "%APPVEYOR_BUILD_FOLDER%\val3dity-windows-x64-v%APPVEYOR_BUILD_VERSION%.zip" "%APPVEYOR_BUILD_FOLDER%\build\Release\val3dity.exe"
  - if exist %APPVEYOR_BUILD_FOLDER%\build\Release\val3dity.exe
    7z a "%APPVEYOR_BUILD_FOLDER%\val3dity-windows-x64-v%APPVEYOR_BUILD_VERSION%.zip" "%OSGEO4W_ROOT%\bin\geos.dll"
  - if exist %APPVEYOR_BUILD_FOLDER%\build\Release\val3dity.exe
    7z a "%APPVEYOR_BUILD_FOLDER%\val3dity-windows-x64-v%APPVEYOR_BUILD_VERSION%.zip" "%OSGEO4W_ROOT%\bin\geos_c.dll"
  - if exist %APPVEYOR_BUILD_FOLDER%\build\Release\val3dity.exe
    7z a "%APPVEYOR_BUILD_FOLDER%\val3dity-windows-x64-v%APPVEYOR_BUILD_VERSION%.zip" "C:\Libraries\boost_1_73_0\lib64-msvc-14.1\boost_filesystem-vc141-mt-x64-1_73.dll"
  - if exist %APPVEYOR_BUILD_FOLDER%\build\Release\val3dity.exe
    7z a "%APPVEYOR_BUILD_FOLDER%\val3dity-windows-x64-v%APPVEYOR_BUILD_VERSION%.zip" "C:\Libraries\boost_1_73_0\lib64-msvc-14.1\boost_system-vc141-mt-x64-1_73.dll"
  
  - if exist C:\deps\CGAL-5.0.2\auxiliary\gmp\lib\libgmp-10.dll
    7z a "%APPVEYOR_BUILD_FOLDER%\val3dity-windows-x64-v%APPVEYOR_BUILD_VERSION%.zip" "C:\deps\CGAL-5.0.2\auxiliary\gmp\lib\libgmp-10.dll"     
  - if exist C:\deps\CGAL-5.0.2\auxiliary\gmp\lib\libmpfr-4.dll
    7z a "%APPVEYOR_BUILD_FOLDER%\val3dity-windows-x64-v%APPVEYOR_BUILD_VERSION%.zip" "C:\deps\CGAL-5.0.2\auxiliary\gmp\lib\libmpfr-4.dll" 
    
    
    
  - if exist C:\deps\CGAL-5.0.2\bin\Release\CGAL_Core-vc140-mt-5.0.2.dll
    7z a "%APPVEYOR_BUILD_FOLDER%\val3dity-windows-x64-v%APPVEYOR_BUILD_VERSION%.zip" "C:\deps\CGAL-5.0.2\bin\Release\CGAL_Core-vc140-mt-5.0.2.dll"        
  
   
    
  - if exist C:\deps\CGAL-5.0.2\bin\Release\CGAL-vc140-mt-5.0.2.dll
    7z a "%APPVEYOR_BUILD_FOLDER%\val3dity-windows-x64-v%APPVEYOR_BUILD_VERSION%.zip" "C:\deps\CGAL-5.0.2\bin\Release\CGAL-vc140-mt-5.0.2.dll"    
    

    
artifacts:
  - path: val3dity-windows-x64-v$(appveyor_build_version).zip
deploy:
  release: val3dity automated release version $(appveyor_build_version)
  description: 'This is an automated val3dity release'
  provider: GitHub
  
  #you need add your own github personal token here
  auth_token:    
    secure: 9ShYWJn/eiwXjAl+2xazcOxbkgQt6FqfJISw0lq/P9UtS6Ng1j8W66u1a5d4w73y
  artifact: val3dity-windows-x64-v$(appveyor_build_version).zip
  draft: true
  prerelease: false
  on:
    branch: master
    configuration: release
 