[bumpver]
current_version = "2.5.0"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit = false
tag = false
push = false

[bumpver.file_patterns]
"src/main.cpp" = [
    'std::string VAL3DITY_VERSION = "{version}";',
]
"src/val3dity.cpp" = [
    'std::string VAL3DITY_VERSION = "{version}";',
]
"docs/conf.py" = [
    "release = u'{version}'",
    "version = u'{version}'",
]
"vcpkg.json" = [
    '"version-string": "{version}"',
]
